### ISSUE TITLE
Workflow on macOS Mojave and Catalina not pasting ref symbol

### ISSUE THREAD

**Issue by mikeozornin** [ruedap/alfred-font-awesome-workflow#111]
Steps to reproduce:
1. Run alfred with fa prefix
2. Type 'trash' query
3. Press Ctrl + Enter

Expected result:
Ref (symbol) pasted.

Actual result:
Icon name pasted.

Here is faw run results.

FA5 workflow:
```
➜  user.workflow.4543DB6D-4242-402A-9A4B-D3C71FC1C4CC ./faw put --name f1f8
fa-trash%                                                                                                                                       ➜  user.workflow.4543DB6D-4242-402A-9A4B-D3C71FC1C4CC

➜  user.workflow.4543DB6D-4242-402A-9A4B-D3C71FC1C4CC ./faw put --code f1f8
f1f8%                                                                                                                                           ➜  user.workflow.4543DB6D-4242-402A-9A4B-D3C71FC1C4CC

➜  user.workflow.4543DB6D-4242-402A-9A4B-D3C71FC1C4CC ./faw put --url f1f8
https://fontawesome.com/icons/trash%            
                                 
➜  user.workflow.4543DB6D-4242-402A-9A4B-D3C71FC1C4CC ./faw put --ref f1f8
trash%
```

If I understand everything correctly, this one is incorrect:
```
➜  user.workflow.4543DB6D-4242-402A-9A4B-D3C71FC1C4CC ./faw put --ref f1f8
trash%
```

Fa4 workflow:
```
user.workflow.EC9AE299-805D-4336-82B6-8A7A2699306C ./faw put --ref f1f8
%
```

macOS (both the same):
Mojave 10.14.6 (18G95)
Catalina 10.15 (19A583)

Workflow version: 5.11.1.0

**Comment by ruedap** [comment]
@mikeozornin Hi, thank you for your report 😄 
It has changed from this version. #98
Did it not work in your environment? 🤔

**Comment by mikeozornin** [comment]
Oh, it seems that not a problem of the workflow. Ligatures (text trash) doen't work in Sketch and Figma without workflow. Will try to understand what's going on.

**Comment by mikeozornin** [comment]
Update fontawesome font: everything working.

Sorry.
