### ISSUE TITLE
Ready for Big Sur and Apple M1

### ISSUE THREAD

**Issue by simeond** [ruedap/alfred-font-awesome-workflow#231]
Hi there.   I am having problems getting this workflow to 'work'.  It doesn't respond to the "fa" query.  

The bug report records an error 

> Code 127: /bin/bash: ./faw: No such file or directory

But it is not clear what should be in this directory or how it should be configured.  

I am running Big Sur, with develop permissions turned on for Alfred.  The problem pre-dated the update anyhow, so not sure it is related.  (As an aside, I've installed the bootstrap icon workflow and that works).

Thanks for your help

**Comment by ruedap** [comment]
Hi @simeond , thank you for your report.
Could you remove your current files and install the [latest version](https://github.com/ruedap/alfred-font-awesome-workflow/releases/latest)? 🤔 
I tested bellow versions and it works.

- Mac mini (M1, 2020)
- macOS Big Sur 11.1
- Alred 4.3 [1205]
- Font Awesome 5.15.1.0

![Screen_Shot_2020-12-18_at_18_33_02](https://user-images.githubusercontent.com/289671/102599893-783f9c80-4161-11eb-9994-9f0e3b19538a.png)

**Comment by simeond** [comment]
that works!  thanks.

(odd because i unstalled and re-installed the other day, and it didn't work.  I must have not done it correctly).

thanks for such a helpful workflow




---
Simeon Duckworth
+ 447979917242

**Comment by ruedap** [comment]
Hi @simeond, thank you for your
