### ISSUE TITLE
Update to 4.7.0

### ISSUE THREAD

**Issue by binarious** [ruedap/alfred-font-awesome-workflow#83]
Great workflow! Would be great to have the new releases included:
https://github.com/FortAwesome/Font-Awesome/releases

**Comment by saltnpixels** [comment]
+1

**Comment by joeworkman** [comment]
Any docs on how to update this? I would be happy to pitch in and help get it updated.

**Comment by joshmedeski** [comment]
I can also help if instructions can be given.

**Comment by joshmedeski** [comment]
Here's more information about the update:
http://fontawesome.io/whats-new/

**Comment by ruedap** [comment]
I am so sorry. I'm late 🙇  I did it just now.
https://github.com/ruedap/alfred-font-awesome-workflow/releases/tag/4.7.0.0

**Comment by joshmedeski** [comment]
No problem @ruedap, thanks for the update!
