### ISSUE TITLE
[High Sierra] Search keyword and received zero results

### ISSUE THREAD

**Issue by aspirewit** [ruedap/alfred-font-awesome-workflow#85]
Workflow:
Version 4.7.0.0

Alfred:
v3.4.1 [860]

OS:
macOS High Sierra
Version 10.13 Beta (17A330h)

**Comment by boileau** [comment]
Same for me with High Sierra 10.13 beta (17A358a)

**Comment by ruedap** [comment]
@aspirewit @boileau Hi, I'm sorry for the late reply. Thank you for the report 😄 
I tried it in the latest versions. There was no problem.

* Workflow:  4.7.0.0
* Alfred: 3.5 [875]
* macOS: High Sierra 10.13

If you still have problems, please reopen this issue.

**Comment by boileau** [comment]
Thanks @ruedap. But I still have the problem.
Blocked on "Search through font awesome Icons"

**Comment by ruedap** [comment]
@boileau Oh, do you use the latest version of Alfred?

**Comment by ptrkcsk** [comment]
I'm having the same problem with Alfred 3.5 and macOS HS.

**Comment by ruedap** [comment]
@ptrkcsk Thank you for the report! I reopen this issue.

**Comment by boileau** [comment]
Yes, last version v3.5 (876)

**Comment by philnorton** [comment]
Not working for me either:

Workflow: 4.7.0.0
Alfred: 3.5
macOS: High Sierra 10.13

Just get the following:

<img width="593" alt="screen shot 2017-10-03 at 12 45 21" src="https://user-images.githubusercontent.com/1104701/31123661-bf501a3e-a838-11e7-8a83-7e365652c167.png">

**Comment by ruedap** [comment]
@philnorton Thanks for the report 😄 

Neither in my clean installed macOS High Sierra nor updated one, this problem has not occurred. I have no idea... 🤔 

![image](https://user-images.githubusercontent.com/289671/31159564-f3bc7af2-a904-11e7-8a83-a8559c962688.png)

**Comment by mikeozornin** [comment]
Have the same.

Maybe this will help. I launched faw from terminal to check what's going on:

```
➜  user.workflow.EC9AE299-805D-4336-82B6-8A7A2699306C ./faw put --ref angle
panic: runtime error: index out of range

goroutine 1 [running]:
main.(*command).put(0xc8200ff678, 0xc82005c810, 0xc8200ff628)
	/Users/ruedap/src/github.com/ruedap/alfred-font-awesome-workflow/command.go:78 +0x7aa
main.glob.func2(0xc8200f61c0)
	/Users/ruedap/src/github.com/ruedap/alfred-font-awesome-workflow/commands.go:34 +0x354
github.com/codegangsta/cli.Command.Run(0x247f88, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2777e0, 0x1d, 0x0, ...)
	/Users/ruedap/src/github.com/codegangsta/cli/command.go:118 +0x1095
github.com/codegangsta/cli.(*App).Run(0xc820100000, 0xc82000a200, 0x4, 0x4, 0x0, 0x0)
	/Users/ruedap/src/github.com/codegangsta/cli/app.go:177 +0xc18
main.main()
	/Users/ruedap/src/github.com/ruedap/alfred-font-awesome-workflow/main.go:12 +0x49
➜  user.workflow.EC9AE299-805D-4336-82B6-8A7A2699306C 
```


I can run some debug version, if you need.

**Comment by mikeozornin** [comment]
Also faw processes seems not stopping and still running in background consuming CPU. Here I have after that ↑ tests:

![screen 20shot 20on 202017-10-04 20at 2013 3a15 3a36](https://user-images.githubusercontent.com/1744928/31170800-2a01e966-a906-11e7-9849-1c9d43124e44.png)

**Comment by xilopaint** [comment]
Same issue of @mikeozornin. The processes are not stopping for me as well.

**Comment by tmerten** [comment]
I happen so see the same problem.

**Comment by ruedap** [comment]
@mikeozornin @xilopaint @tmerten Thanks for your report.

> Maybe this will help. I launched faw from terminal to check what's going on:

Below is the correct arguments. Does this work?

```
$ ./faw find angle
<?xml version="1.0" encoding="UTF-8"?>
<items><item valid="true" arg="f103" uid="f103"><title>angle-double-down</title><subtitle>Paste class name: fa-angle-double-down</subtitle><icon>./icons/fa-angle-double-down.png</icon><unicode>f103</unicode></item><item valid="true" arg="f100" uid="f100"><title>angle-double-left</title><subtitle>Paste class name: fa-angle-double-left</subtitle><icon>./icons/fa-angle-double-left.png</icon><unicode>f100</unicode></item><item valid="true" arg="f101" uid="f101"><title>angle-double-right</title><subtitle>Paste class name: fa-angle-double-right</subtitle><icon>./icons/fa-angle-double-right.png</icon><unicode>f101</unicode></item><item valid="true" arg="f102" uid="f102"><title>angle-double-up</title><subtitle>Paste class name: fa-angle-double-up</subtitle><icon>./icons/fa-angle-double-up.png</icon><unicode>f102</unicode></item><item valid="true" arg="f107" uid="f107"><title>angle-down</title><subtitle>Paste class name: fa-angle-down</subtitle><icon>./icons/fa-angle-down.png</icon><unicode>f107</unicode></item><item valid="true" arg="f104" uid="f104"><title>angle-left</title><subtitle>Paste class name: fa-angle-left</subtitle><icon>./icons/fa-angle-left.png</icon><unicode>f104</unicode></item><item valid="true" arg="f105" uid="f105"><title>angle-right</title><subtitle>Paste class name: fa-angle-right</subtitle><icon>./icons/fa-angle-right.png</icon><unicode>f105</unicode></item><item valid="true" arg="f106" uid="f106"><title>angle-up</title><subtitle>Paste class name: fa-angle-up</subtitle><icon>./icons/fa-angle-up.png</icon><unicode>f106</unicode></item><item valid="true" arg="f071" uid="f071"><title>exclamation-triangle</title><subtitle>Paste class name: fa-exclamation-triangle</subtitle><icon>./icons/fa-exclamation-triangle.png</icon><unicode>f071</unicode></item><item valid="true" arg="f2d3" uid="f2d3"><title>window-close</title><subtitle>Paste class name: fa-window-close</subtitle><icon>./icons/fa-window-close.png</icon><unicode>f2d3</unicode></item><item valid="true" arg="f2d4" uid="f2d4"><title>window-close-o</title><subtitle>Paste class name: fa-window-close-o</subtitle><icon>./icons/fa-window-close-o.png</icon><unicode>f2d4</unicode></item></items>
```

or

```
$ ./faw put -name f103
fa-angle-double-down
```

**Comment by mikeozornin** [comment]
@ruedap, here they are:

```
./faw find angle
<?xml version="1.0" encoding="UTF-8"?>
<items></items>%                    
```

```
./faw put -name f103
panic: runtime error: index out of range

goroutine 1 [running]:
main.(*command).put(0xc42003fa88, 0xc420074780, 0x11d547e)
	/Users/mozornin/Downloads/alfred-font-awesome-workflow-master/command.go:73 +0x70c
main.glob..func2(0xc4200b62c0)
	/Users/mozornin/Downloads/alfred-font-awesome-workflow-master/commands.go:34 +0x304
github.com/codegangsta/cli.HandleAction(0x1197540, 0x11e51c0, 0xc4200b62c0, 0xc420054100, 0x0)
	/Users/mozornin/go/src/github.com/codegangsta/cli/app.go:492 +0x7c
github.com/codegangsta/cli.Command.Run(0x11d5451, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x11ded73, 0x1d, 0x0, ...)
	/Users/mozornin/go/src/github.com/codegangsta/cli/command.go:210 +0xa95
github.com/codegangsta/cli.(*App).Run(0xc420076b60, 0xc42000e100, 0x4, 0x4, 0x0, 0x0)
	/Users/mozornin/go/src/github.com/codegangsta/cli/app.go:255 +0x6f8
main.main()
	/Users/mozornin/Downloads/alfred-font-awesome-workflow-master/main.go:12 +0x4b
```

![screen 20shot 20on 202017-10-11 20at 2015 3a56 3a14](https://user-images.githubusercontent.com/1744928/31441854-20502aa8-ae9d-11e7-8220-89a1df97b205.png)

**Comment by ruedap** [comment]
I built it with the latest version of Go. Could you please try this?

4.7.0.1
https://github.com/ruedap/alfred-font-awesome-workflow/blob/c82db0a9e3a6eacc8b64c9d2e021c4895389731b/Font-Awesome.alfredworkflow

**Comment by mikeozornin** [comment]
Hooray! Worked for me.

![screen 20shot 20on 202017-10-11 20at 2016 3a07 3a58](https://user-images.githubusercontent.com/1744928/31442217-5aab272e-ae9e-11e7-9e2f-1d030af27be0.png)

**Comment by ruedap** [comment]
@mikeozornin Thank you for your contribution 🙇

**Comment by ruedap** [comment]
Version 4.7.0.1 released.
https://github.com/ruedap/alfred-font-awesome-workflow/releases/tag/4.7.0.1

**Comment by rgehan** [comment]
I do still have a `faw` process running in the background and eating all my CPU.

I'm on High Sierra v10.13.3, using Alfred v3.6

**Comment by ruedap** [comment]
@rgehan Hi rgehan, I built it with the latest version of Go. Then I confirmed that it will work with High Sierra and Sierra. Please try it :)
https://github.com/ruedap/alfred-font-awesome-workflow/releases/tag/5.0.6.0
