### ISSUE TITLE
Update to FontAwesome 5

### ISSUE THREAD

**Issue by jpomykala** [ruedap/alfred-font-awesome-workflow#88]
Hey, are you planning to update this workflow to FontAwesome 5? :)

**Comment by ruedap** [comment]
Hi @jpomykala 
Yes, I plan on doing so. but Font Awesome 5.0 has not been published as open source yet.
https://github.com/FortAwesome/Font-Awesome

**Comment by ruedap** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/12199

**Comment by atuttle** [comment]
Looks like it is as of Feb 5th. :)

**Comment by ruedap** [comment]
Ver.5 may not be able to support because there are too many changes 🤔

**Comment by ruedap** [comment]
5.0.6.0 released. This version partially supports Font Awesome ver. 5. For example, classification by class name such as `fas`, `far`, `fab` is not yet supported. Please try it :)
https://github.com/ruedap/alfred-font-awesome-workflow/releases/tag/5.0.6.0
