### ISSUE TITLE
FontAwesome Pro?

### ISSUE THREAD

**Issue by kdumovic** [ruedap/alfred-font-awesome-workflow#97]
Great tool! This is awesome for Figma, as it's currently the best ([only?](https://spectrum.chat/figma?thread=3c3fba4c-0f36-4ca5-b37d-d86ede0a1f31)) way of conveniently inserting fonticons. Is there any way to get this working with the extended icon set in FontAweome Pro?

**Comment by ruedap** [comment]
Sorry, I'm not going to do it because the pro version is not open source.

**Comment by ZLevine** [comment]
Dang, not being able to support Font Awesome Pro makes this unusable for our team unfortunately :( We use a mix of Pro and Free.
